### PR TITLE
Containerize using Docker.

### PR DESCRIPTION
**Pull request by royceschultz**

### CODE REVIEW

**Comment by royceschultz** [comment]
Run 'docker-compose up' to build the containers. This will create 2 instances: a python runner and mongodb server container.
Run 'docker exec -it my_runner /bin/bash' to access the python runner. This will bring up a shell containing the source code. You can run python3 manage_db.py or any other script, just like normal.

**Comment by royceschultz** [comment]
Next steps are to run the mongodb server with authentication and allow it to serve external requests.
Then use replication settings to read from local DB and write to remote DB.

**Comment by ZTWHHH** [comment]
Docker container works well on my mac and my linux virtual machine.

**Comment by chacetrev10** [comment]
Works on my linux machine well. I tried for an hour or so last night to get it working on my windows but had to stop.

**Review by AndrewYeeYee — APPROVED** [review]
Looks good to me. I finally got it running on windows with wsl.

**Pull request merged**
